<?php


// Given the following database structure:

// PRODUCTS (id, name, description, category, price)
// CATEGORIES (id, name, description)
// ORDERS (id, product_id, order_date, customer_name, total_amount)

// Write an SQL query to:

// 1.Display all the products in the category named 'Electronics'.
// 2.For each category, display the name of the category and the total revenue generated 
// by products in that category.
// 3.Display the average price of all products.
// Only write the SQL query, no PHP

$conn = mysqli_connect('localhost', 'root', '1Root2Arsen!');
if ($conn) {
    $query_db = "CREATE DATABASE IF NOT EXISTS shop";
    mysqli_query($conn, $query_db);

    mysqli_select_db($conn, 'shop');

    $query_table_1 = "CREATE TABLE IF NOT EXISTS products (
        id INT NOT NULL AUTO_INCREMENT,
        name VARCHAR(30) NOT NULL,
        description VARCHAR(255) NOT NULL,
        categories VARCHAR(50) NOT NULL,
        price FLOAT(10) NOT NULL,
        PRIMARY KEY(id)
    )";
    mysqli_query($conn, $query_table_1);

    $query_table_2 = "CREATE TABLE IF NOT EXISTS categories (
        id INT NOT NULL AUTO_INCREMENT,
        name VARCHAR(50) NOT NULL,
        description VARCHAR(255) NOT NULL,
        PRIMARY KEY(id)
    )";
    mysqli_query($conn, $query_table_2);

    $query_table_3 = "CREATE TABLE IF NOT EXISTS orders (
        orders_id INT NOT NULL AUTO_INCREMENT,
        product_id INT NOT NULL,
        order_data INT NOT NULL,
        customer_name VARCHAR(50),
        total_amount INT,
        PRIMARY KEY(orders_id),
        FOREIGN KEY(product_id) REFERENCES products(id),
        FOREIGN KEY(order_data) REFERENCES categories(id)
    )";
    mysqli_query($conn, $query_table_3);
    // 1.Display all the products in the category named 'Electronics'.
    $display_1 = "SELECT * FROM products WHERE categories='electronics'";
    $result = mysqli_query($conn, $display_1);
    // $names = mysqli_fetch_assoc($result);
    $names = mysqli_fetch_all($result, MYSQLI_ASSOC);


    foreach($names as $value) {
        echo $value['name'].'<br>';
    }

// 2.For each category, display the name of the category and the total revenue generated by products in that category.

// $query_display_2 = "SELECT products.name FROM products";
// SELECT CATEGORIES.name AS category_name, SUM(ORDERS.total_amount) AS total_revenue
// FROM PRODUCTS
// INNER JOIN CATEGORIES
// ON PRODUCTS.category = CATEGORIES.id
// INNER JOIN ORDERS
// ON PRODUCTS.id = ORDERS.product_id
// GROUP BY CATEGORIES.name

    mysqli_close($conn);
}
